### ISSUE TITLE
PollingBlockTracker - encountered an error while attempting to update latest block:

### ISSUE THREAD

**Issue by faizyboy1** [MetaMask/eth-block-tracker#110]
I am creating my dapp through walletconnect and infura when i use walletconnect web3provider and pass infura id to initalize the web3provider this error starts to appear and it sends so many requests to infura endpoint more than 100k in few hours and exceed the limits of requests of infura and it make difficult to further test and develop the dapp. The error is occuring in `poling .js` file while fetching the latest block. I have no clue what to do. I have not post any query on github so if any thing left from my side i can explain further thanks.

````
const provider = new WalletConnectProvider({

      infuraId: "8031b681fe9f440ba9dedc43c6d3e780",
      connector: connector,
      // chainId: connector.chainId,
      qrcode: false,
    });
````
poling.js
```
async _updateLatestBlock () {
    // fetch + set latest block
    console.log("Updating latest Block1");
    const waitFor = delay => new Promise(resolve => setTimeout(resolve, delay));
    await waitFor(5000);
    const latestBlock = await this._fetchLatestBlock()
    this._newPotentialLatest(latestBlock)
  }
```

   i tried to tackle by myself by adding two lines of `setTimeout` Thanks

**Comment by mcmire** [comment]
It seems that `@walletconnect/web3-provider` uses our [`web3-provider-engine`](https://github.com/MetaMask/web3-provider-engine) package, which is using an older version of _this_ package. However, we no longer support `web3-provider-engine`, and it seems that WalletConnect doesn't support `@walletconnect/web3-provider`, either, as [the last real commit was in 2019](https://github.com/WalletConnect/walletconnect-monorepo/commits/v1.0.0-next.0/packages/web3-provider) and [this provider doesn't appear in their active development branch](https://github.com/WalletConnect/walletconnect-monorepo).

`@walletconnect/web3-provider` seems very specific to MetaMask, so if that's the case, then why not use [our guide to get the current MetaMask provider](https://docs.metamask.io/guide/ethereum-provider.html#basic-usage) and then pass that to `ethers` via [its Web3Provider class](https://docs.ethers.io/v5/api/providers/other/#Web3Provider)? This way you don't need to pass an Infura key (since you're going through MetaMask to make requests). Or, if you want to talk to Infura directly, then you can use [`ethers.providers.InfuraProvider`](https://docs.ethers.io/v5/api/providers/api-providers/#InfuraProvider).

**Comment by Shehryar2** [comment]
@mcmire  Thanks for the reply. I am using mobile development to create my dapp so i am using walletconnect to connect with metamsk or any other wallet.

**Comment by anhnh-yoong** [comment]
@mcmire Thanks for the reply. Can I disable alert?

**Comment by mcmire** [comment]
I am going to close this issue since there is a solution for this, but let me know if you have any more thoughts.
