### ISSUE TITLE
Generating lots of redundant calls

### ISSUE THREAD

**Issue by chejazi** [MetaMask/eth-block-tracker#21]
My app uses the ZeroClientProvider to connect to infura and query the transaction logs; initialization logic:  https://github.com/channel/channel.github.io/blob/master/app/src/scripts/initialize.jsx#L27

The trouble I'm facing is that for each web3 LogFilter.get() request I make, the block tracker enqueues a getLogs request that never stops polling. As time goes on the amount of data being fetched grows and grows. You can see the pattern in the network tab at https://channel.github.io

My hack solution is to add `self._blockTracker.stop()` right after this line: https://github.com/MetaMask/provider-engine/blob/master/index.js#L37

I figure there's something off with the way requests are being queued up - not sure if this is the right place to report the issue but figured it was worth a shot.

I've attached a screenshot showing the tracker doing it's polling, and then (while the page is idle) making a bunch of getLogs requests, presumably once a new block comes in:
<img width="855" alt="polling" src="https://cloud.githubusercontent.com/assets/2603535/26235524/8a5c4b2e-3c20-11e7-9de2-4361aae9f837.png">

**Comment by flyswatter** [comment]
I just found the same thing! I have a feeling this is about to be my top priority for the coming week.

https://github.com/MetaMask/metamask-plugin/issues/1458

**Comment by kumavis** [comment]
my guess is you refreshed your dapp many times, and it installed new filters without uninstalling them. the problem is really that the life cycle of the filters is not tied to the dapp. we've just made this change in metamask.

**Comment by chejazi** [comment]
I'm using the ZeroClientProvider (zero.js) directly and connecting to infura for users that don't have metamask installed - the screenshot above is from my app window, not inpage.js. I'm also calling Filter.get(callback) so I don't think I need to uninstall anything, right? I thought I only need to uninstall for Filter.watch.

**Comment by flyswatter** [comment]
I believe this behavior had me incorrectly blaming the ENS-Registrar-Dapp for the polling leak, when they also only use Event.get(), no `.watch()`:

https://github.com/ethereum/ens-registrar-dapp/issues/153

I'm not sure this is a problem with `eth-block-tracker`, though, this looks much more like a `web3-provider-engine/subproviders/filter` bug.

**Comment by flyswatter** [comment]
Here's what it looks like right now when we call Event.get:

![screen shot 2017-05-25 at 3 12 38 pm](https://cloud.githubusercontent.com/assets/542863/26472816/a7e50c9e-415c-11e7-90df-e2c63c4cb7e3.png)

**Comment by flyswatter** [comment]
Okay so looks like two bugs to me:

- BlockTracker walking is slow and inefficient at times.
- Web3's contract abstraction treats `get` as a subscription, and regardless of `fromBlock` and `toBlock` parameters, it is continuously requesting new logs for the filter.

**Comment by flyswatter** [comment]
Okay so part of that before was because I had the filter subprovider in the client.  Moving it out, here's the division of labor right now, when a user creates an `Event` object and calls `get()` on it (the exact order of events between client and providerEngine I haven't gotten to yet):

Client says: sendAsync  eth_newFilter [Object]
Client says: sendAsync  eth_getFilterLogs ["0x01"]

ProviderEngine returns a filter ID.
ProviderEngine calls `getLogs` to the RPC for that range, returns 

ProviderEngine continues block walking, and on each new block, calls an updated `getLogs()` to the RPC for the new block with the other params.

**Comment by flyswatter** [comment]
Alright, I've tracked this down to [a bug in web3.js](https://github.com/ethereum/web3.js/issues/879).

Every time you create an `Event` object, it registers a `Filter` in MetaMask's provider, and never unsubscribes it.

For this reason, until this is fixed in web3, for getting some logs, I have to recommend using other methods of fetching logs.

The lowest level approach looks like this:

```javascript

    web3.currentProvider.sendAsync({
      method: 'eth_getLogs',
      params: [options],
    }, callback);

```

Where `options` is a [filter options object](https://github.com/ethereum/wiki/wiki/JavaScript-API#parameters-46).

I think there may be a nice place for a convenience library around that method now, that only requests what you ask for.

Leaving this open for now because I want more time for us to consider if there's anything we can do at this layer to mitigate this problem.

**Comment by chejazi** [comment]
Nice work. I remember adding a calls to `Filter.stopWatching()` in my code, both right after the `Filter.get()` call and within its callback function, but the problem didn't go away. Web3 looks like it properly deregisters if I call that method. I'm wondering if the issue might not be isolated to Web3?

**Comment by flyswatter** [comment]
It might not be. I think [we are at least partially responsible](https://github.com/MetaMask/metamask-plugin/issues/1503) for the poor performance here, but there is a bit of a perfect storm that's come together here.

Partly leaving this open because I'm suspicious there are other things at play still.

**Comment by chejazi** [comment]
Solution to this problem described in https://github.com/MetaMask/provider-engine/issues/150, closing
